name: micro_app_auth
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ##firebase
  firebase_auth: 4.15.2

  google_sign_in: 6.1.6
  sign_in_with_apple: 5.0.0

  shared_preferences: 2.2.2
  get_it: 7.6.4
  mocktail: 0.3.0
  dartz: 0.10.1
  equatable: 2.0.5
  email_validator: 2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
