name: Dart CI

on: [pull_request]

jobs:
  analyze_and_fix:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código do repositório
      - uses: actions/checkout@v2

      # Configura o SDK Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5" # Especifique a versão do Flutter aqui. Remova essa linha se quiser a versão estável mais recente.

      # Instala as dependências do Flutter
      - name: Install dependencies
        run: flutter pub get

      # Tentativa de correção automática de problemas
      - name: Auto-fix issues
        run: dart fix --apply

      # Roda o Dart Analyzer para verificar se ainda existem problemas
      - name: Run Dart Analyzer
        run: dart analyze

      # Faz commit e push das correções, se houver
      - name: Commit fixes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Apply dart fixes" || echo "No changes to commit"
          git push
